spring:
  profiles:
    active: local
# db 실행 1순위: edit configurations - active profiles 란에 mysql or local 등 작성한 환경으로 실행된다.
# edit configurations 에 명시하지 않을 시 이 곳에서 mysql or local 중 작성한 환경으로 실행된다. (local = h2)

# mysql or h2 등 여러 DB를 설정하고자 하면 구분선을 이용해 여러개의 profile을 설정한다.
# profile 에 따른 db 선택은 위에서 명시한 방법으로 할 수 있다.
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?useUnicode=true&characterEncoding=utf8
      username: study
      password: yohan
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always # mysql 배치 스키마 항상 생성
#      table-prefix: TABLE_ # prefix 변경하려면 먼저 배치 테이블 이름도 변경해서 생성해야함
    job:
      names: ${job.name:NONE} # Edit configuration 에서 job.name 지정 가능, bean으로 등록한 job과 이름이 같아야함
      enabled: true # 스프링 Job 자동실행 여부, 디폴트: true


